services:
    postgres:
      image: pgvector/pgvector:pg17
      container_name: vowlt-postgres
      environment:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
      # Don't expose to host in production (internal network only)
      expose:
        - "5432"
      volumes:
        - postgres_data_prod:/var/lib/postgresql/data
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
        interval: 10s
        timeout: 5s
        retries: 5
        start_period: 10s
      restart: unless-stopped
      networks:
        - vowlt-network

    api:
      build:
        context: .
        dockerfile: docker/Dockerfile.api
      container_name: vowlt-api
      environment:
        POSTGRES_HOST: postgres  # Docker service name
        POSTGRES_PORT: 5432
        POSTGRES_DB: ${POSTGRES_DB}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT:-Production}
        JWT_SECRET: ${JWT_SECRET}
        JWT_ISSUER: ${JWT_ISSUER}
        JWT_AUDIENCE: ${JWT_AUDIENCE}
        OPENAI_API_KEY: ${OPENAI_API_KEY}
      expose:
        - "5000"
      depends_on:
        postgres:
          condition: service_healthy
      restart: unless-stopped
      networks:
        - vowlt-network

    web:
      build:
        context: .
        dockerfile: docker/Dockerfile.web
      container_name: vowlt-web
      expose:
        - "80"
      restart: unless-stopped
      networks:
        - vowlt-network

    nginx:
      image: nginx:alpine
      container_name: vowlt-nginx
      ports:
        - "80:80"
        - "443:443"
      volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        - ./nginx/ssl:/etc/nginx/ssl:ro
        - ./nginx/letsencrypt:/etc/letsencrypt:ro
      depends_on:
        - api
        - web
      restart: unless-stopped
      networks:
        - vowlt-network

volumes:
  postgres_data_prod:

networks:
  vowlt-network:
    driver: bridge
